// Code generated by MockGen. DO NOT EDIT.
// Source: practice-run/chat (interfaces: roomService)
//
// Generated by this command:
//
//	mockgen -destination mocks/mock_room_service.go -mock_names roomService=RoomService -package=mocks . roomService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	room "practice-run/room"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// RoomService is a mock of roomService interface.
type RoomService struct {
	ctrl     *gomock.Controller
	recorder *RoomServiceMockRecorder
	isgomock struct{}
}

// RoomServiceMockRecorder is the mock recorder for RoomService.
type RoomServiceMockRecorder struct {
	mock *RoomService
}

// NewRoomService creates a new mock instance.
func NewRoomService(ctrl *gomock.Controller) *RoomService {
	mock := &RoomService{ctrl: ctrl}
	mock.recorder = &RoomServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RoomService) EXPECT() *RoomServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m_2 *RoomService) AddMember(ctx context.Context, r *room.Room, m room.Member) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AddMember", ctx, r, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *RoomServiceMockRecorder) AddMember(ctx, r, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*RoomService)(nil).AddMember), ctx, r, m)
}

// CreateRoom mocks base method.
func (m *RoomService) CreateRoom(ctx context.Context, roomName string) (*room.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, roomName)
	ret0, _ := ret[0].(*room.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *RoomServiceMockRecorder) CreateRoom(ctx, roomName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*RoomService)(nil).CreateRoom), ctx, roomName)
}

// RemoveMember mocks base method.
func (m_2 *RoomService) RemoveMember(ctx context.Context, r *room.Room, m room.Member) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RemoveMember", ctx, r, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *RoomServiceMockRecorder) RemoveMember(ctx, r, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*RoomService)(nil).RemoveMember), ctx, r, m)
}

// SendMessage mocks base method.
func (m_2 *RoomService) SendMessage(ctx context.Context, r *room.Room, m room.Member, message string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMessage", ctx, r, m, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *RoomServiceMockRecorder) SendMessage(ctx, r, m, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*RoomService)(nil).SendMessage), ctx, r, m, message)
}
