// Code generated by MockGen. DO NOT EDIT.
// Source: practice-run/handler (interfaces: ChatService)
//
// Generated by this command:
//
//	mockgen -destination mocks/chat_service_mock.go -package mocks . ChatService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	service "practice-run/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// JoinChannel mocks base method.
func (m *MockChatService) JoinChannel(ctx context.Context, channelName string, member service.ChannelMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinChannel", ctx, channelName, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinChannel indicates an expected call of JoinChannel.
func (mr *MockChatServiceMockRecorder) JoinChannel(ctx, channelName, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinChannel", reflect.TypeOf((*MockChatService)(nil).JoinChannel), ctx, channelName, member)
}

// LeaveChannel mocks base method.
func (m *MockChatService) LeaveChannel(ctx context.Context, channelName string, member service.ChannelMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveChannel", ctx, channelName, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveChannel indicates an expected call of LeaveChannel.
func (mr *MockChatServiceMockRecorder) LeaveChannel(ctx, channelName, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveChannel", reflect.TypeOf((*MockChatService)(nil).LeaveChannel), ctx, channelName, member)
}

// SendMessage mocks base method.
func (m *MockChatService) SendMessage(ctx context.Context, channelName string, member service.ChannelMember, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, channelName, member, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatServiceMockRecorder) SendMessage(ctx, channelName, member, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatService)(nil).SendMessage), ctx, channelName, member, message)
}
