// Code generated by MockGen. DO NOT EDIT.
// Source: practice-run/handler2 (interfaces: ChatService)
//
// Generated by this command:
//
//	mockgen -destination mocks/chat_service_mock.go -package mocks . ChatService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// GetUpdates mocks base method.
func (m *MockChatService) GetUpdates(ctx context.Context, username string) (<-chan string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdates", ctx, username)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdates indicates an expected call of GetUpdates.
func (mr *MockChatServiceMockRecorder) GetUpdates(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdates", reflect.TypeOf((*MockChatService)(nil).GetUpdates), ctx, username)
}

// JoinChannel mocks base method.
func (m *MockChatService) JoinChannel(ctx context.Context, username, channelName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinChannel", ctx, username, channelName)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinChannel indicates an expected call of JoinChannel.
func (mr *MockChatServiceMockRecorder) JoinChannel(ctx, username, channelName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinChannel", reflect.TypeOf((*MockChatService)(nil).JoinChannel), ctx, username, channelName)
}

// LeaveChannel mocks base method.
func (m *MockChatService) LeaveChannel(ctx context.Context, username, channelName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveChannel", ctx, username, channelName)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveChannel indicates an expected call of LeaveChannel.
func (mr *MockChatServiceMockRecorder) LeaveChannel(ctx, username, channelName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveChannel", reflect.TypeOf((*MockChatService)(nil).LeaveChannel), ctx, username, channelName)
}

// SendMessage mocks base method.
func (m *MockChatService) SendMessage(ctx context.Context, username, channelName, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, username, channelName, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatServiceMockRecorder) SendMessage(ctx, username, channelName, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatService)(nil).SendMessage), ctx, username, channelName, message)
}
